name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        run: |
          cd $GITHUB_WORKSPACE/frontend
          yarn install

      - name: Install server dependencies
        run: |
          cd $GITHUB_WORKSPACE/server
          npm install

      - name: Pull latest code
        run: |
          cd $GITHUB_WORKSPACE
          git pull origin main

      - name: Start frontend
        run: |
          cd $GITHUB_WORKSPACE/frontend
          yarn dev

      - name: Start server
        run: |
          cd $GITHUB_WORKSPACE/server
          npm start
